---
repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0 # Update with 'pre-commit autoupdate'
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        exclude: tests
