---
# This workflow will run unit tests and deploy the application to a
# target environment

name: Deploy

on: push

jobs:
  unit-test:
    uses: GSA-TTS/identity-idva-token-service/.github/workflows/unit-tests.yaml@main
  setup-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shumatepf/identity-idva-cf-setup/service-setup@v2.2.1
        with:
          require-postgres: "true"
  deploy:
    needs: [unit-test, setup-db]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: GSA-TTS/identity-idva-cf-setup@v2
        id: cf-setup
        with:
          cf-username: ${{ secrets.CF_USERNAME }}
          cf-password: ${{ secrets.CF_PASSWORD }}
          cf-org: ${{ secrets.CF_ORG }}

      - name: Deploy application
        run: cf push --vars-file vars.yaml
          --var ENVIRONMENT_NAME=${{ steps.cf-setup.outputs.target-environment }}
          --var SECRET_KEY=${{ secrets.SECRET_KEY }}
          --strategy rolling
